---
# file: playbook-remove-prelink.yml
#
# Main playbook for the prelink removal project.

- name: Create ephemeral inventory groups
  hosts: all
  tasks:
    - name: Group hosts based on OS distribution and major version
      group_by:
        key: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}"
      # Run even if we were passed `--check`
      check_mode: no

- name: Disable and remove prelink from RHEL 7 hosts
  hosts: RedHat_7
  become: yes
  gather_facts: no
  vars_prompt:
    - name: reboot_choice
      prompt: "Would you like to reboot boxes if they change (y/n)?"
      default: "n"
      unsafe: yes
      private: no
  handlers:
    - name: reboot boxes
      when: reboot_choice == 'y' or reboot_choice == 'Y'
      include_tasks: tasks/reboot-boxes.yml
  tasks:

    - name: gather package information
      package_facts:

    - when: "'prelink' in ansible_facts.packages"
      block:

        - name: disable prelinking in /etc/sysconfig/prelink
          replace:
            path: /etc/sysconfig/prelink
            regexp: 'PRELINKING=yes'
            replace: 'PRELINKING=no'
          notify: reboot boxes

        - name: undo prelink actions
          shell: prelink -uav >> /var/log/prelink/prelink.log 2>&1
          notify: reboot boxes

        - name: delete prelink cache
          file:
            path: /etc/prelink.cache
            state: absent
          notify: reboot boxes

        - name: remove prelink package
          yum:
            name: prelink
            state: absent
          notify: reboot boxes

# vim:ft=yaml.ansible:
