---
# file: playbook-remove-prelink.yml
#
# Main playbook for the prelink removal project.

- name: Create ephemeral inventory groups
  hosts: all
  tasks:
    - name: Group hosts based on OS distribution and major version
      group_by:
        key: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}"
      # Run even if we were passed `--check`
      check_mode: no

- name: Disable and remove prelink from RHEL 7 hosts
  hosts: RedHat_7
  become: yes
  gather_facts: no
  tasks:

    - name: gather package information
      package_facts:

    - when: "'prelink' in ansible_facts.packages"
      block:

        - name: disable prelinking in /etc/sysconfig/prelink
          replace:
            path: /etc/sysconfig/prelink
            regexp: 'PRELINKING=yes'
            replace: 'PRELINKING=no'

        - name: undo prelink actions
          shell: prelink -uav >> /var/log/prelink/prelink.log 2>&1

        - name: delete prelink cache
          file:
            path: /etc/prelink.cache
            state: absent

        - name: remove prelink package
          yum:
            name: prelink
            state: absent

# vim:ft=yaml.ansible:
